# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pr:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: Simple variable group

steps:
- task: DownloadSecureFile@1
  name: settingsxml
  displayName: 'Download settings.xml'
  inputs:
    secureFile: 'settings.xml'

- task: PowerShell@2
  displayName: 'Configure settings.xml'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/.m2"
      Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/settings.xml"
      Get-ChildItem -Path "${HOME}"
      Get-ChildItem -Path "${HOME}/.m2"

- task: Maven@3
  displayName: 'PMD check'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'pmd:pmd'
    options: '-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: true
    pmdRunAnalysis: true

- task: Bash@3
  displayName: 'Checking results of PMD'
  inputs:
    targetType: 'inline'
    script: |
      FILE="server/target/site/pmd.html"
      if [ -f "$FILE" ];
      then
        echo "File $FILE exist."
        exit 1
      else
        echo "File $FILE does not exist"
      fi
    failOnStderr: true

- task: Maven@3
  displayName: 'Maven validate'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'validate'
    options: '-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: false

- task: Maven@3
  displayName: 'Maven compile'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile'
    options: '-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: false

- task: Maven@3
  displayName: 'Maven test'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    options: '-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export commitUUID="$(git rev-parse HEAD)"
      export CODACY_PROJECT_TOKEN=$(CODACY_PROJECT_TOKEN)
      curl -Ls -o codacy-coverage-reporter-assembly.jar $(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url')
      java -Dhttps.protocols=TLSv1.2,TLSv1.1,TLSv1 -jar codacy-coverage-reporter-assembly.jar report -l Java --commit-uuid $TOTO -r server/target/site/jacoco/jacoco.xml

- task: Maven@3
  displayName: 'Maven package'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    options: '-DskipTests -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    checkStyleRunAnalysis: false
    pmdRunAnalysis: false